services:
  php:
    build: ./backend
    container_name: php
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8080 -t public/
    environment:
      SYMFONY_ENV: dev
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:18.3
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - database:/var/lib/postgresql/data

  react:
    image: node:25
    container_name: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/home/node/app
      - frontend_node_modules:/home/node/app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0

volumes:
  database:
  frontend_node_modules: