<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260430184458 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cv_language (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level VARCHAR(10) NOT NULL, cv_id INT NOT NULL, language_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_45F49471CFE419E2 ON cv_language (cv_id)');
        $this->addSql('CREATE INDEX IDX_45F4947182F1BAF4 ON cv_language (language_id)');
        $this->addSql('CREATE TABLE experience (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company VARCHAR(255) NOT NULL, job_title VARCHAR(255) NOT NULL, start_date DATE NOT NULL, end_date DATE DEFAULT NULL, description TEXT DEFAULT NULL, position INT NOT NULL, is_current BOOLEAN NOT NULL, resume_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_590C103D262AF09 ON experience (resume_id)');
        $this->addSql('CREATE TABLE language (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE resume (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, birth_date DATE DEFAULT NULL, email VARCHAR(255) NOT NULL, driving_licenses JSON DEFAULT NULL, phone_number VARCHAR(255) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, job_title VARCHAR(255) DEFAULT NULL, catch_phrase TEXT DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE resume_tag (resume_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (resume_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_1153051BD262AF09 ON resume_tag (resume_id)');
        $this->addSql('CREATE INDEX IDX_1153051BBAD26311 ON resume_tag (tag_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE training (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, school VARCHAR(255) NOT NULL, degree VARCHAR(255) NOT NULL, graduation_year SMALLINT NOT NULL, description TEXT DEFAULT NULL, resume_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D5128A8FD262AF09 ON training (resume_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE cv_language ADD CONSTRAINT FK_45F49471CFE419E2 FOREIGN KEY (cv_id) REFERENCES resume (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv_language ADD CONSTRAINT FK_45F4947182F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE experience ADD CONSTRAINT FK_590C103D262AF09 FOREIGN KEY (resume_id) REFERENCES resume (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE resume_tag ADD CONSTRAINT FK_1153051BD262AF09 FOREIGN KEY (resume_id) REFERENCES resume (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resume_tag ADD CONSTRAINT FK_1153051BBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE training ADD CONSTRAINT FK_D5128A8FD262AF09 FOREIGN KEY (resume_id) REFERENCES resume (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cv_language DROP CONSTRAINT FK_45F49471CFE419E2');
        $this->addSql('ALTER TABLE cv_language DROP CONSTRAINT FK_45F4947182F1BAF4');
        $this->addSql('ALTER TABLE experience DROP CONSTRAINT FK_590C103D262AF09');
        $this->addSql('ALTER TABLE resume_tag DROP CONSTRAINT FK_1153051BD262AF09');
        $this->addSql('ALTER TABLE resume_tag DROP CONSTRAINT FK_1153051BBAD26311');
        $this->addSql('ALTER TABLE training DROP CONSTRAINT FK_D5128A8FD262AF09');
        $this->addSql('DROP TABLE cv_language');
        $this->addSql('DROP TABLE experience');
        $this->addSql('DROP TABLE language');
        $this->addSql('DROP TABLE resume');
        $this->addSql('DROP TABLE resume_tag');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE training');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
